version: '3.8'

services:
  app:
    build: .
    ports:
      - "50051:50051"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"