apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-backend-deployment
  labels:
    app: client-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client-backend
  template:
    metadata:
      labels:
        app: client-backend
    spec:
      containers:
        - name: client-backend
          image: app/client-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"