// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.6
// source: proto/profiler_output.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Profiler_SendProfilerOutput_FullMethodName = "/profiler_output.Profiler/SendProfilerOutput"
)

// ProfilerClient is the client API for Profiler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfilerClient interface {
	SendProfilerOutput(ctx context.Context, in *ProfilerOutputRequest, opts ...grpc.CallOption) (*Response, error)
}

type profilerClient struct {
	cc grpc.ClientConnInterface
}

func NewProfilerClient(cc grpc.ClientConnInterface) ProfilerClient {
	return &profilerClient{cc}
}

func (c *profilerClient) SendProfilerOutput(ctx context.Context, in *ProfilerOutputRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Profiler_SendProfilerOutput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfilerServer is the server API for Profiler service.
// All implementations must embed UnimplementedProfilerServer
// for forward compatibility
type ProfilerServer interface {
	SendProfilerOutput(context.Context, *ProfilerOutputRequest) (*Response, error)
	mustEmbedUnimplementedProfilerServer()
}

// UnimplementedProfilerServer must be embedded to have forward compatible implementations.
type UnimplementedProfilerServer struct {
}

func (UnimplementedProfilerServer) SendProfilerOutput(context.Context, *ProfilerOutputRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendProfilerOutput not implemented")
}
func (UnimplementedProfilerServer) mustEmbedUnimplementedProfilerServer() {}

// UnsafeProfilerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfilerServer will
// result in compilation errors.
type UnsafeProfilerServer interface {
	mustEmbedUnimplementedProfilerServer()
}

func RegisterProfilerServer(s grpc.ServiceRegistrar, srv ProfilerServer) {
	s.RegisterService(&Profiler_ServiceDesc, srv)
}

func _Profiler_SendProfilerOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfilerOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilerServer).SendProfilerOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profiler_SendProfilerOutput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilerServer).SendProfilerOutput(ctx, req.(*ProfilerOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Profiler_ServiceDesc is the grpc.ServiceDesc for Profiler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Profiler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "profiler_output.Profiler",
	HandlerType: (*ProfilerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendProfilerOutput",
			Handler:    _Profiler_SendProfilerOutput_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/profiler_output.proto",
}
