apiVersion: v1
kind: Service
metadata:
  name: client-backend-service
spec:
  selector:
    app: client-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer