name: Build and Publish Docker Images on Release

on:
  release:
    types:
      - published
      - released
      - prereleased

env:
  GITHUB_SHA: ${{ github.sha }}
  RELEASE_VERSION: ${{ github.event.release.tag_name }}

jobs:
  build-and-push-datasource:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push datasource image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: app/back/datasource
          file: app/back/datasource/Dockerfile
          tags: |
            handoe/hostasphere-datasource:release-${{ env.RELEASE_VERSION }}
            handoe/hostasphere-datasource:latest

  build-and-push-rest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push rest image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: app/back/rest
          file: app/back/rest/Dockerfile
          tags: |
            handoe/hostasphere-rest:release-${{ env.RELEASE_VERSION }}
            handoe/hostasphere-rest:latest

  build-and-push-front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push front image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: app/front
          file: app/front/Dockerfile
          tags: |
            handoe/hostasphere-front:release-${{ env.RELEASE_VERSION }}
            handoe/hostasphere-front:latest

  build-and-push-server-pricing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push server pricing image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: server/pricing
          file: server/pricing/Dockerfile
          tags: |
            handoe/hostasphere-server-pricing:release-${{ env.RELEASE_VERSION }}
            handoe/hostasphere-server-pricing:latest
