name: Build and Publish Docker Images (app/front)

on:
  push:
    branches:
      - main
    paths:
      - 'app/front/**'
      - '.github/workflows/docker-publish-app-front.yml'

env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract short SHA
        id: short-sha
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push front image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: app/front
          file: app/front/Dockerfile
          tags: |
            handoe/hostasphere-front:sha-${{ env.SHORT_SHA }}
            handoe/hostasphere-front:latest
