name: Build and Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/datasource
            ghcr.io/${{ github.repository }}/rest
            ghcr.io/${{ github.repository }}/front
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build and push datasource image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: app/back/datasource/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository }}/datasource:${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push rest image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: app/back/rest/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository }}/rest:${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push front image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: app/front/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository }}/front:${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}